inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/channels/**/*'
    - 'app/jobs/*'
    - 'bin/*'
    - 'config/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'features/**/*'
    - 'test/**/*'
    - 'lib/**/*'
    - 'script/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Exclude:
    - '**/*'
