version: '2'
services:
  app:
    build: .
    restart: always
    ports:
    - 3000:3000/tcp
    command:
    - bundle
    - exec
    - rails
    - s
    - -p
    - '3000'
    - -b
    - 0.0.0.0
    volumes:
    - ./:/vagas
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: vagas_pass
      POSTGRES_USER: vagas
